[[language]]
name = "python"
scope = "source.python"
injection-regex = "py(thon)?"
file-types = ["py", "pyi", "py3", "pyw", "ptl", "rpy", "cpy", "ipy", "pyt", { glob = ".python_history" }, { glob = ".pythonstartup" }, { glob = ".pythonrc" }, { glob = "SConstruct" }, { glob = "SConscript" }]
shebangs = ["python", "uv"]
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json"]
comment-token = "#"
language-servers = ["pyright"]
# TODO: pyls needs utf-8 offsets
indent = { tab-width = 4, unit = "    " }

[language-server.pylsp.config.pylsp]
plugins.ruff.enabled = true
plugins.black.enabled = true
plugins.pylsp_mypy.enabled = true

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
